version: "3"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuserpass
      TZ: Asia/Tokyo
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
#      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d # 起動時にDBを初期構築する場合
      - ./log/mysql:/var/log/mysql
      - ./data/mysql:/var/lib/mysql # データを永続化する場合
    ports:
      - "3306:3306" # ホストマシン上のmigrationで必要

  python:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: app
      DB_USER: appuser
      DB_PASSWORD: appuserpass
      DJANGO_SETTINGS_MODULE: config.settings.local
    volumes:
      - .:/root/app
    ports:
      - "8000:8000"
    depends_on:
      - db
