version: "3"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuserpass
      TZ: Asia/Tokyo
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
#      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d # 起動時にDBを初期構築する場合
      - ./log/mysql:/var/log/mysql
      - ./data/mysql:/var/lib/mysql # データを永続化する場合
    ports:
      - "3306:3306"

  s3:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniouserpass
    volumes:
      - ./data/s3/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    ports:
      - "8080:8000"
    volumes:
      - ./data/dynamodb/data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

  python:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: app
      DB_USER: appuser
      DB_PASSWORD: appuserpass
      DJANGO_SETTINGS_MODULE: config.settings.local
    volumes:
      - .:/root/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - s3
      - dynamodb
