# Generated by Django 4.0.2 on 2022-02-05 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='パフォーマー')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'db_table': 'performer',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='プログラム名')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonster.performer', verbose_name='パフォーマー')),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=4, unique=True, verbose_name='コード')),
                ('name', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='スタジオ')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'db_table': 'studio',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='開始日時')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonster.performer', verbose_name='パフォーマー')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonster.program', verbose_name='プログラム')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonster.studio', verbose_name='スタジオ')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('studio', 'start_time'), name='schedule_uidx_1'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('performer', 'name'), name='program_uidx_1'),
        ),
    ]
