# Generated by Django 4.0.2 on 2022-02-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='コード')),
                ('name', models.CharField(db_index=True, max_length=16, verbose_name='スタジオ')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
            ],
            options={
                'db_table': 'studio',
            },
        ),
    ]
