# Generated by Django 4.0.2 on 2022-02-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmonster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='code',
            field=models.CharField(db_index=True, max_length=4, unique=True, verbose_name='コード'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(db_index=True, max_length=16, unique=True, verbose_name='スタジオ'),
        ),
    ]
