# Generated by Django 4.0.2 on 2022-02-11 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bmonster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='受講日')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('modified_datetime', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmonster.program', verbose_name='プログラム')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'db_table': 'attendance_history',
            },
        ),
        migrations.AddConstraint(
            model_name='attendancehistory',
            constraint=models.UniqueConstraint(fields=('user', 'program'), name='attendance_history_uidx_1'),
        ),
    ]
