# Generated by Django 4.0.2 on 2022-02-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmonster', '0002_attendancehistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancehistory',
            name='attendance_date',
            field=models.DateTimeField(verbose_name='受講日'),
        ),
    ]
