# Generated by Django 4.0.2 on 2022-02-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmonster', '0004_remove_attendancehistory_attendance_history_uidx_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancehistory',
            name='attendance_datetime',
            field=models.DateTimeField(verbose_name='受講日時'),
        ),
    ]
